from .usuario import Usuario
from .tecnico import Tecnico
from .solicitud import Solicitud
from .cotizacion import Cotizacion
from .historial_solicitud import HistorialSolicitud
from .resena import Resena
from .documento_tecnico import DocumentoTecnico
from .notificacion import Notificacion
from .servicio import Servicio
from .region import Region
from .comuna import Comuna
from .tecnico_servicio import TecnicoServicio
from .tecnico_comuna import TecnicoComuna